#!/bin/bash

#PBS -N test9_pro2_h
#PBS -o ./log/$PBS_JOBNAME.log
#PBS -e ./log/$PBS_JOBNAME.err
#PBS -l nodes=1:ppn=12
#PBS -l walltime=124:00:00
#PBS -q batch

workdir=$HOME/workspace/MFMCG/
jobcmd=$workdir/"`echo $PBS_JOBNAME | awk -F '_' '{print $1}'`".py
binlog=$workdir/profiles/profmetrp-bin.log
asclog=$workdir/profiles/profmetrp.log
profiler=$workdir/profmetrp.py


date
source $HOME/.bashrc
python -m cProfile -o $binlog $jobcmd 
date
python $profiler $binlog > $asclog
