from graphene import graphene
a = graphene(width=4,length=7,ledge=1.42,boundary='p',holes=[[0,5]])
print "size:",a.size(1)
print "holes:",a.holes('2d')
#print "lined hole-pairs:", a.linedholepairs(a.line)
print "dvertex:",a.dvertex('2d')
print "danglingc:",a.danglingc('2d')
print "ndvertex:",a.ndvertex()
print "pbn of hole:",a.pbneighb([0,5])
print a.nlines()
print a.size(1)
b = a.lslines()
print len(b)
from drawing import *
drawhoneycomb(a,output="h.eps")
drawgraphene(a,output="g.eps")
